using HealthCardAPI.Models;
using QuestPDF.Fluent;          
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace HealthCardAPI.Services
{
    public class HealthCardPdfGenerator
    {
        public static byte[] Generate(Patient patient, Nominee nominee)
        {
            

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30);
                    page.DefaultTextStyle(x => x.FontSize(11).FontFamily(Fonts.Arial));

                    page.Content().AlignCenter().Column(col => 
                    {
                        // Draw the ID Card centered on the page
                        col.Item().Width(400).Border(1).BorderColor(Colors.Grey.Lighten2).Background(Colors.White).Column(card =>
                        {
                            // 1. Header with Gradient-like color
                            card.Item().Background("#f5576c").Padding(15).Row(row =>
                            {
                                row.RelativeItem().Column(c =>
                                {
                                    c.Item().Text("SMART HEALTH CARD").FontSize(18).Bold().FontColor(Colors.White);
                                    c.Item().Text("Digital Health Identity").FontSize(10).FontColor(Colors.White.Medium);
                                });
                                // Placeholder for Logo/Icon
                                row.ConstantItem(40).AlignRight().Text("🏥").FontSize(24);
                            });

                            // 2. Main Content
                            card.Item().Padding(20).Row(row =>
                            {
                                // Left: Photo Placeholder
                                row.ConstantItem(100).Column(photoCol =>
                                {
                                    photoCol.Item().Height(100).Width(100).Background(Colors.Grey.Lighten4).AlignMiddle().AlignCenter().Text("PHOTO").FontSize(10).FontColor(Colors.Grey.Darken1);
                                });

                                row.Spacing(20);

                                // Right: Details
                                row.RelativeItem().Column(details =>
                                {
                                    details.Spacing(5);

                                    details.Item().Text(t => { t.Span("Name: ").Bold().Color(Colors.Grey.Darken2); t.Span(patient.Name).SemiBold().FontSize(14); });
                                    details.Item().Text(t => { t.Span("Card No: ").Bold().Color(Colors.Grey.Darken2); t.Span(patient.HealthCardNumber).FontColor("#f5576c"); });
                                    
                                    details.Item().PaddingTop(5).LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
                                    details.Item().PaddingTop(5);

                                    details.Item().Text(t => { t.Span("DOB: ").Bold(); t.Span($"{patient.DateOfBirth:dd MMM yyyy}"); });
                                    details.Item().Text(t => { t.Span("Gender: ").Bold(); t.Span(patient.Gender); });
                                    details.Item().Text(t => { t.Span("Blood Group: ").Bold(); t.Span(patient.BloodGroup); });
                                    details.Item().Text(t => { t.Span("Mobile: ").Bold(); t.Span(patient.PhoneNumber.ToString()); });
                                    details.Item().Text(t => { t.Span("Nominee: ").Bold(); t.Span(nominee?.Name ?? "N/A"); });
                                });
                            });

                            // 3. Footer / Barcode Area
                            card.Item().Padding(15).Background(Colors.Grey.Lighten5).Row(row => 
                            {
                                row.RelativeItem().Column(c => 
                                {
                                    c.Item().Text($"Issued: {DateTime.Now:dd-MM-yyyy}").FontSize(9).FontColor(Colors.Grey.Darken1);
                                    c.Item().Text("Keep this card safe").FontSize(8).Italic().FontColor(Colors.Grey.Darken1);
                                });

                                row.ConstantItem(100).AlignRight().AlignMiddle().Text("||| || ||| ||").FontSize(12); // Mock Barcode
                            });
                        });
                    });

                    page.Footer().AlignCenter().Text("Generated by AarogyaCard Portal").FontSize(9).FontColor(Colors.Grey.Medium);
                });
            });

            return document.GeneratePdf();
        }
    }
}
